
server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true


    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=board_dvach
    username: postgres
    password: 1234

logging:
  level:
    org:
      hibernate:
        type: trace

#values
page:
  size: 20


