spring:
  application:
    name: notification-service
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"
  profiles:
    active: ${envTarget:default}
    group:
      dev: deployed, oauth
      default: simpleSecurity
  zipkin:
    base-url: "http://localhost:9411"
  rabbitmq:
    addresses: "localhost:5672"


http:
  protocol: http
  host: localhost
  sec:
    path: /
  oauthPath: /oauth/token

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8085

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key





