spring:
  application:
    name: video-service
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"
  profiles:
    active: ${envTarget:default}
    group:
      dev: deployed, oauth
      default: simpleSecurity
  zipkin:
    base-url: http://localhost:9411
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
http:
  protocol: http
  host: localhost
  sec:
    path: /
  oauthPath: /oauth/token

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8086

api:
  video:
    address: "/api/v1/video"

data:
  video:
    folder: "/data/video"
  previewPicture:
    folder: "/data/previewPicture"
  chunkRate: 1000000
