spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"
  profiles:
    active: ${envTarget:default}
    group:
      dev: deployed, oauth
      default: simpleSecurity
  zipkin:
    base-url: http://localhost:9411
http:
  protocol: http
  host: localhost
  sec:
    path: /
  oauthPath: /oauth/token

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8082

client:
  live-test-client-id: live-test
  live-test-client-secret: derderder
  open-api-id: open-api
  open-api-secret: erererere





